### ISSUE TITLE
laravel 5.1 support

### ISSUE THREAD

**Issue by selam** [sboo/laravel5-mailjet#3]
laravel 5.1 LTS support will be nice i guess we dont need to much changes

**Comment by prspace** [comment]
No update? I think this repo is dead.

**Comment by sboo** [comment]
The project I used it for unfortunately died. so it was hard and useless for me to work on it. So right now I don't have  test case to work on it myself.

**Comment by prspace** [comment]
I'm on a project with mailjet with laravel 5.2 can i do some help?

**Comment by sboo** [comment]
Where does it fail right now? dependencies or anything more serious?

**Comment by giovanniorigins** [comment]
It currently fails on dependencies
